const channelCreate = require('./channelCreate');
const channelDelete = require('./channelDelete');
const channelPinsUpdate = require('./channelPinsUpdate');
const channelUpdate = require('./channelUpdate');
// const debug = require('./debug');
const emojiCreate = require('./emojiCreate');
const emojiDelete = require('./emojiDelete');
const emojiUpdate = require('./emojiUpdate');
// const error = require('./error');
const guildBanAdd = require('./guildBanAdd');
const guildBanRemove = require('./guildBanRemove');
const guildCreate = require('./guildCreate');
const guildDelete = require('./guildDelete');
const guildIntegrationsUpdate = require('./guildIntegrationsUpdate');
const guildMemberAdd = require('./guildMemberAdd');
const guildMemberAvailable = require('./guildMemberAvailable');
const guildMemberRemove = require('./guildMemberRemove');
const guildMembersChunk = require('./guildMembersChunk');
const guildMemberSpeaking = require('./guildMemberSpeaking');
const guildMemberUpdate = require('./guildMemberUpdate');
const guildUnavailable = require('./guildUnavailable');
const guildUpdate = require('./guildUpdate');
// const invalidated = require('./invalidated');
const inviteCreate = require('./inviteCreate');
const inviteDelete = require('./inviteDelete');
const message = require('./message');
const messageDelete = require('./messageDelete');
const messageDeleteBulk = require('./messageDeleteBulk');
const messageReactionAdd = require('./messageReactionAdd');
const messageReactionRemove = require('./messageReactionRemove');
const messageReactionRemoveAll = require('./messageReactionRemoveAll');
const messageReactionRemoveEmoji = require('./messageReactionRemoveEmoji');
const messageUpdate = require('./messageUpdate');
const presenceUpdate = require('./presenceUpdate');
const rateLimit = require('./rateLimit');
const ready = require('./ready');
const roleCreate = require('./roleCreate');
const roleDelete = require('./roleDelete');
const roleUpdate = require('./roleUpdate');
// const shardDisconnect = require('./shardDisconnect');
// const shardError = require('./shardError');
// const shardReady = require('./shardReady');
// const shardReconnecting = require('./shardReconnecting');
// const shardResume = require('./shardResume');
const typingStart = require('./typingStart');
const userUpdate = require('./userUpdate');
const voiceStateUpdate = require('./voiceStateUpdate');
// const warn = require('./warn');
const webhookUpdate = require('./webhookUpdate');

module.exports = client => {
	client.on('channelCreate', channel => channelCreate(channel)); // A channel is created
	client.on('channelDelete', channel => channelDelete(channel)); // A channel is deleted
	client.on('channelPinsUpdate', (channel, time) => channelPinsUpdate(channel, time)); // A message is pinned or a message is unpinned
	client.on('channelUpdate', (oldChannel, newChannel) => channelUpdate(oldChannel, newChannel)); // A channel is updated
	// client.on('debug', info => debug(info)); // Debug information?
	client.on('emojiCreate', emoji => emojiCreate(emoji)); // An emoji is created
	client.on('emojiDelete', emoji => emojiDelete(emoji)); // An emoji is deleted
	client.on('emojiUpdate', (oldEmoji, newEmoji) => emojiUpdate(oldEmoji, newEmoji)); // An emoji is updated
	// client.on('error', error => error(error)); // An error?
	client.on('guildBanAdd', (guild, user) => guildBanAdd(guild, user)); // A member is banned
	client.on('guildBanRemove', (guild, user) => guildBanRemove(guild, user)); // A member is unbanned
	client.on('guildCreate', guild => guildCreate(guild)); // Bot joins a guild
	client.on('guildDelete', guild => guildDelete(guild)); // Bot leaves a guild
	client.on('guildIntegrationsUpdate', guild => guildIntegrationsUpdate(guild)); // Integrations are updated
	client.on('guildMemberAdd', member => guildMemberAdd(member)); // Someone joins
	client.on('guildMemberAvailable', member => guildMemberAvailable(member)); // Documentation: Emitted whenever a member becomes available in a large guild
	client.on('guildMemberRemove', member => guildMemberRemove(member)); // Someone leaves
	client.on('guildMembersChunk', (members, guild, chunk) => guildMembersChunk(members, guild, chunk)); // Documentation: Emitted whenever a chunk of guild members is received (all members come from the same guild).
	client.on('guildMemberSpeaking', (member, speaking) => guildMemberSpeaking(member, speaking)); // Speaking status updated
	client.on('guildMemberUpdate', (oldMember, newMember) => guildMemberUpdate(oldMember, newMember)); // A member is updated
	client.on('guildUnavailable', guild => guildUnavailable(guild)); // A guild is unavailable, maybe because of an outage
	client.on('guildUpdate', (oldGuild, newGuild) => guildUpdate(oldGuild, newGuild)); // A guild is updated
	// client.on('invalidated', () => invalidated());
	client.on('inviteCreate', invite => inviteCreate(invite)); // An invite is created
	client.on('inviteDelete', invite => inviteDelete(invite)); // An invited is deleted
	client.on('message', msg => message(msg)); // Someone sends a message
	client.on('messageDelete', message => messageDelete(message)); // A message is deleted
	client.on('messageDeleteBulk', messages => messageDeleteBulk(messages)); // Bulk messages are deleted
	client.on('messageReactionAdd', (messageReaction, user) => messageReactionAdd(messageReaction, user)); // Someone reacts to a message
	client.on('messageReactionRemove', (messageReaction, user) => messageReactionRemove(messageReaction, user)); // Someone unreacts to a message
	client.on('messageReactionRemoveAll', message => messageReactionRemoveAll(message)); // All reactions to a message are removed
	client.on('messageReactionRemoveEmoji', reaction => messageReactionRemoveEmoji(reaction)); // Bot removes a reaction
	client.on('messageUpdate', (oldMessage, newMessage) => messageUpdate(oldMessage, newMessage)); // A message is updated
	client.on('presenceUpdate', (oldPresence, newPresence) => presenceUpdate(oldPresence, newPresence)); // Someone's presence changed
	client.on('rateLimit', rateLimitInfo => rateLimit(rateLimitInfo)); // Client is ratelimited
	client.once('ready', () => ready(client)); // When ready, only runs once
	client.on('roleCreate', role => roleCreate(role)); // A role is created
	client.on('roleDelete', role => roleDelete(role)); // A role is deleted
	client.on('roleUpdate', (oldRole, newRole) => roleUpdate(oldRole, newRole)); // A role is updated
	// client.on('shardDisconnect', (event, id) => shardDisconnect(event, id)); // A shard's websocket is disconnected and won't reconnect
	// client.on('shardError', (error, shardID) => shardError(error, shardID)); // A shard's websocket has encountered an error
	// client.on('shardReady', (id, unavailableGuilds) => shardReady(id, unavailableGuilds)); // A shard is ready
	// client.on('shardReconnecting', id => shardReconnecting(id)); // Attempt to reconnect
	// client.on('shardResume', (id, replayedEvents) => shardResume(id, replayedEvents)); // A shard resumes successfully
	client.on('typingStart', (channel, user) => typingStart(channel, user)); // A user started typing in a channel
	client.on('userUpdate', (oldUser, newUser) => userUpdate(oldUser, newUser)); // A user is updated
	client.on('voiceStateUpdate', (oldState, newState) => voiceStateUpdate(oldState, newState)); // Member joins/leaves, mutes/unmutes
	// client.on('warn', info => warn(info)); // Documentation: Emitted for general warnings.
	client.on('webhookUpdate', channel => webhookUpdate(channel)); // A webhook is updated
}