name: Versioning
on: [push]
jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.JS V18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup Git Enviornment
        run: |
          git config --global user.name = "${{ github.triggering_actor }}"
          git config --global user.email = "${{ github.triggering_actor }}@users.noreply.github.com"
          git config --global user.password = "${{ github.token }}"
      - id: bump
        name: Bump Version
        run: |
          npm run bump
          npm i
          rm -rf node_modules
      - name: Push and Tag Commits
        run: |
          git add -A
          git commit -m "Bump version to $VERSION"
          git tag -a "$VERSION" -m "Tag for version $VERSION"
          git push --follow-tags
        env:
          VERSION: ${{ env.VERSION }}
  release:
    runs-on: ubuntu-latest
    needs: bump
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag: ${{ needs.bump.outputs.version }}